config/routes.rb
Rails.application.routes.draw do

  get 'about/about' => 'about#about'

  get 'learning/academia'
  get 'learning/other'

  get 'projects/index' => 'projects#index'
  get 'projects/fourletters'
  get 'projects/thermostat'
  get 'projects/bowling'
  get 'projects/target-pay'

  get 'home/welcome'
  
  root 'home#welcome'
  
  namespace :learning do
    namespace :computing do
      resources :instructors, :sites
    end
    resources :computings
  end
  
  resources :users
  
  namespace :tefl do
    resources :links
  end

  namespace :instakilo do
    root 'posts#index'
    resources :posts do 
      resources :comments
      resources :likes
      resources :dislikes
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :coursesSite
  belongs_to :instructor
end

app/models/courses_site.rb
class CoursesSite < ActiveRecord::Base
  has_many :courses
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  has_many :courses
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/technology.rb
class Technology < ActiveRecord::Base
end

app/models/tefl.rb
class Tefl < ActiveRecord::Base
  belongs_to :user
  linkformat = /\A(http:\/\/|https:\/\/)\w+\.\w+/
  validates :name, :uniqueness => :true
  validates :link, :uniqueness => :true, :format => linkformat
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
    @projects = Project.all.reverse
    @techs = Technology.all
  end
end

app/controllers/learning/computing/instructors_controller.rb
class Learning::Computing::InstructorsController < ApplicationController
  def show
  end

  def create
    @inst = Instructor.new(instructor_params)
    if @inst.save
      flash[:notice] = "Instructor added to database."
    else
      flash[:error] = "There was a problem Please try again."
    end
    redirect_to learning_computing_instructors_path
  end

  def edit
    @inst = Instructor.find(params[:id])
  end

  def update
  end

  def destroy
  end

  def index
    @inst = Instructor.all
    @new = Instructor.new
  end
  
  private
  def instructor_params
    params.require(:instructor).permit(:id, :name, :profile)
  end
  
end

app/controllers/learning/computing/sites_controller.rb
class Learning::Computing::SitesController < ApplicationController
  def index
    @site = CoursesSite.all
    @new = CoursesSite.new
  end

  def create
    @new = CoursesSite.new(site_params)
    if @new.save
      flash[:notice] = "Site successfully saved"
    else
      flash[:error] = "Sorry, it didn't work. Please try again."
    end
    redirect_to learning_computing_sites_path    
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
  end
  
  private
  def site_params
    params.require(:courses_site).permit(:id, :name, :address)
  end
end

app/controllers/learning/computings_controller.rb
class Learning::ComputingsController < ApplicationController
  def index
    @course = Course.all
    @inst = Instructor.all
    @site = CoursesSite.all
    @new = Course.new
  end
  
  def create
    @new = Course.new(course_params)
    if @new.save
        flash[:notice] = "Your course has been updated."
      else
        flash[:error] = "Sorry, there was a problem! Please try again."
    end
    redirect_to learning_computings_path
  end
  
  def edit
    @inst = Instructor.all
    @site = CoursesSite.all
    @course = Course.find(params[:id])
  end
  
  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
        flash[:notice] = "Your course has been updated."
        redirect_to learning_computings_path
      else
        flash[:error] = "Sorry, there was a problem! Please try again."
    end
    
  end
  
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to learning_computings_path
  end

  def show
  end
  
  private
  def course_params
    params.require(:course).permit(:id, :name, :courses_site_id, :rating, :complete, :description, :learnt, :img, :address, :instructor_id)
  end
end

app/controllers/learning_controller.rb
class LearningController < ApplicationController
  def academia
  end

  def computing
  end

  def other
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/controllers/tefl/links_controller.rb
class Tefl::LinksController < ApplicationController
  def index
    @link = Tefl.all
    @new = Tefl.new
  end

  def new
    @new = Tefl.new
  end
  
  def create
    @new = Tefl.new(tefl_params)
    if @new.save
        redirect_to tefl_links_path
        flash[:notice] = "Thank you. Your link has been added."
      else
        render "new"
    end
  end

  def destroy
    @link = Tefl.find(params[:id])
    @link.destroy
    redirect_to tefl_links_path
  end

  def edit
    @link = Tefl.find(params[:id])
  end

  def show
  end

  def update
    @link = Tefl.find(params[:id])
    if Tefl.update(tefl_params)
      redirect_to tefl_links_path
      flash[:notice] = "Thank you. Your post has been updated."
    else
      render "edit"
    end
  end
  
  private
  def tefl_params
    params.require(:tefl).permit(:id, :user_id, :name, :link, :description, :visited, :created_at, :commit)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learning/computing/instructors_helper.rb
module Learning::Computing::InstructorsHelper
end

app/helpers/learning/computing/sites_helper.rb
module Learning::Computing::SitesHelper
end

app/helpers/learning/computing_helper.rb
module Learning::ComputingHelper
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tefl/links_helper.rb
module Tefl::LinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/learning/academia.html.erb
<h1>Academia</h1>
<p>Here I give a brief overview of my academic background, acheivements and certifications.</p>
<div class="blob">
  <h2><%= link_to "The University of Nottingham", "https://www.nottingham.ac.uk/" %> <small>2006-2010</small></h2>
  <h4>BA Hons 2:1 Modern Language Studies</h4>
  <p>
    Here I studied a four-year sandwich course, which involved two years' academic study in Nottingham,
    a year abroad - with no formal academic assessment, and a fourth year back in Nottingham.
  </p>
  <p>
    The first two years were incredible, and I developed as much socially as I did academically, that's
    not to say I didn't study, I did study and passed all my exams and had a great time. In these years I was
    introduced to Slovene (that's the language they speak in Slovenia, NOT Slovakia!) and continued
    my studies of the French and Spanish languages, as well as attending several courses on French/Spanish/Latin
    American literature and history.
  </p>
  <p>
    My third year was an adventure. I spent the first few months of the academic year studying in Ljubljana
    - the capital of Slovenia - and met loads of new people from a plethora of different countries.
    I spent most of the winter working in a ski shop, in the French Alps. I spent the last part of
    the academic year at a language school in the Spanish city of San Sebastian, where I "learnt" to
    surf, I can go (a little) more than 10m now!
  </p>
  <p>
    My final year was back in Nottingham, and I also started to learn a little Serbian, as well as
    continuing with my other languages.
  </p>
</div>
<div class="blob">
  <h2><%= link_to "Uplands Community College", "http://www.uplandscc.com/" %> <small>1999-2006</small></h2>
  <h4>A-levels, AS-levels and GCSEs</h4>
  <p>
    I started at Uplands, which was my local comprehensive school in 1999, and made a lot of friends
    there. I was always a good student, and only got in trouble a few times for not having homework.
    I guess I tended to be the annoying student who would always point out the teachers' mistakes ("Miss!
    Miss! You forgot to dot the 'i'!"). I played rugby for the school and took part in the school orchestra
    as its lead bassoonist. I admit there was only one bassoonist, but I still want the title! My favourite
    subjects at school were maths, chemistry and foreign languages. I thought English was pointless and
    history was boring and just remembering a load of dates was too much effort. I didn't mind the other
    subjects.
    
    I decided to study French, Spanish, maths, chemistry and biology to AS-level. Trying to leave
    the door open to studying medicine and languages. At the end of the year, I decided to go down
    the languages path, as I wasn't really sure what I wanted to do and this wouldn't lock me into
    anything in particular.
  </p>
</div>

app/views/learning/computing/instructors/create.html.erb
<h1>Learning::Computing::Instructors#create</h1>
<p>Find me in app/views/learning/computing/instructors/create.html.erb</p>

app/views/learning/computing/instructors/destroy.html.erb
<h1>Learning::Computing::Instructors#destroy</h1>
<p>Find me in app/views/learning/computing/instructors/destroy.html.erb</p>

app/views/learning/computing/instructors/edit.html.erb
<h1>Learning::Computing::Instructors#edit</h1>
<p>Find me in app/views/learning/computing/instructors/edit.html.erb</p>

app/views/learning/computing/instructors/index.html.erb
<h1>Learning::Computing::Instructors#index</h1>
<table>
  <thead>
    <td>ID</td>
    <td>Name</td>
    <td>Profile address</td>
  </thead>
  <%= form_for @new, url: {action:"create"} do |f| %>
  <tr><td>New:</td><td><%= f.text_field :name %></td><td><%= f.text_field :profile %><%= f.submit %></td></tr>
  <% end %>
  <% @inst.each do |i| %>
  <tr>
    <td><%= i.id %></td>
    <td><%= i.name %></td>
    <td><%= i.profile %></td>
  </tr>
  <% end %>
</table>

app/views/learning/computing/instructors/show.html.erb
<h1>Learning::Computing::Instructors#show</h1>
<p>Find me in app/views/learning/computing/instructors/show.html.erb</p>

app/views/learning/computing/instructors/update.html.erb
<h1>Learning::Computing::Instructors#update</h1>
<p>Find me in app/views/learning/computing/instructors/update.html.erb</p>

app/views/learning/computings/create.html.erb
<h1>Learning::Computing#create</h1>
<p>Find me in app/views/learning/computing/create.html.erb</p>

app/views/learning/computings/destroy.html.erb
<h1>Learning::Computing#destroy</h1>
<p>Find me in app/views/learning/computing/destroy.html.erb</p>

app/views/learning/computings/edit.html.erb
<h1 style="display:inline">Edit <%= @course.name %></h1>&nbsp;|&nbsp;<small><%= link_to "delete", learning_computing_path(@course.id), method: :delete %></small>
<%= form_for @course, url: {action: "update"}, html: {class: "blob"} do |f| %>
<table>
  <tr><td>Name of course:</td><td><%= f.text_field :name %></td></tr>
  <tr><td>Course address:</td><td><%= f.text_field :address %></td></tr>
  <tr><td>On:</td><td><%= f.collection_select :courses_site_id, @site.order(:name), :id, :name, include_blank: true %></td></tr>
  <tr><td>By:</td><td><%= f.collection_select :instructor_id, @inst.order(:name), :id, :name, include_blank: true %></td></tr>
  <tr><td>Description:</td><td><%= f.text_area :description %></td></tr>
  <tr><td>Learnt:</td><td><%= f.text_area :learnt %></td></tr>
  <tr><td>Course rating:</td><td><%= f.number_field :rating %></td></tr>
  <tr><td>Course progress:</td><td><%= f.number_field :complete %></td></tr>
  <tr><td>Image:</td><td><%= f.text_field :img %></td></tr>
</table>
  <%= f.submit "Add link" %>
<% end %>

app/views/learning/computings/index.html.erb
<h1>Computing learning</h1>

<P>
  Below you can find a list of the various different courses I've taken and what I've learnt from them.
</P>

<% @course.each do |c| %>
  <div class="blob">
    <div class="course_title">
      <h2 style="display:inline"><%= link_to c.name, c.address %></h2> <small style="display:inline"></small>
      <h5>by <%= link_to Instructor.find(c.instructor_id).name, Instructor.find(c.instructor_id).profile %> on <%= link_to CoursesSite.find(c.courses_site_id).name, CoursesSite.find(c.courses_site_id).address %></h5>
    </div>
    <span class="course_body">
      <p></p><h4>Description</h4>
      <%= c.description %></p>
      <p><h4>What I learnt</h4>
      <%= c.learnt %></p>
      <p>
        <span>My rating: <%= c.rating %>/5</span>
        <br class="mob">
        <span>
          My progress: <%= c.complete %>%
          <svg width="416" height="20" class="progpc">
            <rect width="416" height="21" rx="10" ry="10" style="fill:#EEE" />
            <rect x="8" y="8" width="<%= c.complete*4 %>" height="5" rx="3" ry="3" style="fill:#<%= (c.complete == 100)? "0F0":(c.complete > 49)? "9B3": "F00" %>;" />
          </svg>
          <svg width="116" height="20" class="progmob">
            <rect width="116" height="21" rx="10" ry="10" style="fill:#EEE" />
            <rect x="8" y="8" width="<%= c.complete %>" height="5" rx="3" ry="3" style="fill:#<%= (c.complete == 100)? "0F0":(c.complete > 49)? "9B3": "F00" %>;" />
          </svg>
        </span>
      </P>
    </span>
  </div>
<% end %>
<!--
<h1>Add a course</h1>
<%= form_for @new, url: {action: "create"}, html: {class: "blob"} do |f| %>
<table>
  <tr><td>Name of course:</td><td><%= f.text_field :name %></td></tr>
  <tr><td>Course address:</td><td><%= f.text_field :address %></td></tr>
  <tr><td>On:</td><td><%= f.collection_select :courses_site_id, @site.order(:name), :id, :name, include_blank: true %></td></tr>
  <tr><td>By:</td><td><%= f.collection_select :instructor_id, @inst.order(:name), :id, :name, include_blank: true %></td></tr>
  <tr><td>Description:</td><td><%= f.text_area :description %></td></tr>
  <tr><td>Learnt:</td><td><%= f.text_area :learnt %></td></tr>
  <tr><td>Course rating:</td><td><%= f.number_field :rating %></td></tr>
  <tr><td>Course progress:</td><td><%= f.number_field :complete %></td></tr>
  <tr><td>Image:</td><td><%= f.text_field :img %></td></tr>
</table>
  <%= f.submit "Add link" %>
<% end %>
-->

app/views/learning/computings/show.html.erb
<h1>Learning::Computing#show</h1>
<p>Find me in app/views/learning/computing/show.html.erb</p>

app/views/learning/computings/update.html.erb
<h1>Learning::Computing#update</h1>
<p>Find me in app/views/learning/computing/update.html.erb</p>

app/views/learning/other.html.erb
<h1>Various Other Acheivements</h1>

<div class="blob">
  <h4>Certificate in English Language Teaching to Adults (CELTA) <small>September 2010</small></h4>
  <p>
    I completed my CELTA in Valencia, in Spain. This is the most standard and reputable certificate
    for teachers of English as a foreign language, awarded by the University of Cambridge.
  </p>
</div>

<div class="blob">
  <h4> Driving <small>summer 2010</small></h4>
  <p>I have a full, clean driving licence.</p>
</div>