config/routes.rb
Rails.application.routes.draw do

  get 'about/about' => 'about#about'

  get 'learning/academia'
  get 'learning/other'

  get 'projects/index' => 'projects#index'
  get 'projects/fourletters'
  get 'projects/thermostat'
  get 'projects/bowling'
  get 'projects/target-pay'

  get 'home/welcome'
  
  root 'home#welcome'
  
  namespace :learning do
    namespace :computing do
      resources :instructors, :sites
    end
    resources :computings
  end
  
  resources :users
  
  namespace :tefl do
    resources :links
  end

  namespace :instakilo do
    root 'posts#index'
    resources :posts do 
      resources :comments
      resources :likes
      resources :dislikes
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :coursesSite
  belongs_to :instructor
end

app/models/courses_site.rb
class CoursesSite < ActiveRecord::Base
  has_many :courses
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  has_many :courses
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/technology.rb
class Technology < ActiveRecord::Base
end

app/models/tefl.rb
class Tefl < ActiveRecord::Base
  belongs_to :user
  linkformat = /\A(http:\/\/|https:\/\/)\w+\.\w+/
  validates :name, :uniqueness => :true
  validates :link, :uniqueness => :true, :format => linkformat
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
    @projects = Project.all.reverse
    @techs = Technology.all
  end
end

app/controllers/learning_controller.rb
class LearningController < ApplicationController
  def academia
  end

  def computing
  end

  def other
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tefl/links_helper.rb
module Tefl::LinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">
  <head>
    <title>Tom's site</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta property="og:site_name" content="Tom's site">
<meta property="og:title" content="Home">
<meta property="og:url" content="http://tomy8s.herokuapp.com">
<meta property="og:type" content="website">
<meta property="og:image" content="https://scontent-lhr3-1.xx.fbcdn.net/v/t1.0-1/p160x160/13239061_10102022617097918_7430461033153205691_n.jpg?oh=e47e3ba3d26de5b22470493d40b06fe0&oe=57C9E11F">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render partial:"partials/header" %>
    <% flash.each do |c, m| %>
        <%= content_tag(:div, m, class: c) %>
    <% end %>
    <main>
    <%= yield %>
    </main>
    <%= render partial:"partials/footer" %>
  </body>
</html>

app/views/partials/_footer.html.erb
    <footer>
      <p>
        <%= link_to image_tag("GitHub-Mark/PNG/GitHub-Mark-32px.png"), "https://github.com/Tomy8s" %>&nbsp;&nbsp;
        <i>By <%= link_to "T.Yates","mailto:t.w.yates@hotmail.co.uk" %></i>&nbsp;&nbsp;
        <%= link_to image_tag("CodeWars-Mark/logo-square-paper-bg.jpg", size: "32"), "https://www.codewars.com/users/Tomy8s" %>
      </p>
    </footer>
  </body>
</html>

app/views/partials/_header.html.erb
    <div id="top">
        <header>
            <h1 id="title"><%= link_to "Tom's Site", root_path %></span></h1>
        <div id="user">
        </div>
        </header>
        <nav id="navtop">
            <ul>
                <li>
                    <%= link_to "About me", about_about_path %>
                </li>
                <br class="mob">
                <li>
                    <%= link_to "TEFL", tefl_links_path %>
                </li>
                <br class="mob">
                <li>
                    <%= link_to "Learning", learning_academia_path %>
                    <ul>
                        <li>
                            <%= link_to "Academia", learning_academia_path %>
                        </li>
                        <li>
                            <%= link_to "Computing", learning_computings_path %>
                        </li>
                        <li>
                            <%= link_to "Other", learning_other_path %>
                        </li>
                    </ul><!--Learning-->
                </li>
                <br class="mob">
                <li>
                    <%= link_to "Projects", projects_index_path %>
                    <ul>
                      <li>
                        <%= link_to "Four letters", projects_fourletters_path %>
                      </li>
                      <li>
                        <%= link_to "Thermostat", projects_thermostat_path %>
                      </li>
                      <li>
                        <%= link_to "Bowling", projects_bowling_path %>
                      </li>
                      <li>
                        <a href="http://typhp.herokuapp.com/projects/maths_init.php">Maths</a>
                      </li>
                      <li>
                        <a href="http://typhp.herokuapp.com/projects/calendar.php">Calendar</a>
                      </li>
                      <li>
                        <a href="http://typhp.herokuapp.com/projects/game_of_life_init.php">Conway's Game</a>
                      </li>
                      <li>
                        <a href="http://typhp.herokuapp.com/projects/gal_viewer.php">Pic. Viewer</a>
                      </li>
                    </ul>
                </li><!--Projects-->
            </ul><!--All items-->
        </nav><!--Navtop-->
    </div><!--Top-->