config/routes.rb
Rails.application.routes.draw do

  get 'about/about' => 'about#about'

  get 'learning/academia'
  get 'learning/other'

  get 'projects/index' => 'projects#index'
  get 'projects/fourletters'
  get 'projects/thermostat'
  get 'projects/bowling'
  get 'projects/target-pay'

  get 'home/welcome'
  
  root 'home#welcome'
  
  namespace :learning do
    namespace :computing do
      resources :instructors, :sites
    end
    resources :computings
  end
  
  resources :users
  
  namespace :tefl do
    resources :links
  end

  namespace :instakilo do
    root 'posts#index'
    resources :posts do 
      resources :comments
      resources :likes
      resources :dislikes
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :coursesSite
  belongs_to :instructor
end

app/models/courses_site.rb
class CoursesSite < ActiveRecord::Base
  has_many :courses
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  has_many :courses
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/technology.rb
class Technology < ActiveRecord::Base
end

app/models/tefl.rb
class Tefl < ActiveRecord::Base
  belongs_to :user
  linkformat = /\A(http:\/\/|https:\/\/)\w+\.\w+/
  validates :name, :uniqueness => :true
  validates :link, :uniqueness => :true, :format => linkformat
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
    @projects = Project.all.reverse
    @techs = Technology.all
  end
end

app/controllers/learning/computings_controller.rb
class Learning::ComputingsController < ApplicationController
  def index
    @course = Course.all
    @inst = Instructor.all
    @site = CoursesSite.all
    @new = Course.new
  end
  
  def create
    @new = Course.new(course_params)
    if @new.save
        flash[:notice] = "Your course has been updated."
      else
        flash[:error] = "Sorry, there was a problem! Please try again."
    end
    redirect_to learning_computings_path
  end
  
  def edit
    @inst = Instructor.all
    @site = CoursesSite.all
    @course = Course.find(params[:id])
  end
  
  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
        flash[:notice] = "Your course has been updated."
        redirect_to learning_computings_path
      else
        flash[:error] = "Sorry, there was a problem! Please try again."
    end
    
  end
  
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to learning_computings_path
  end

  def show
  end
  
  private
  def course_params
    params.require(:course).permit(:id, :name, :courses_site_id, :rating, :complete, :description, :learnt, :img, :address, :instructor_id)
  end
end

app/controllers/learning_controller.rb
class LearningController < ApplicationController
  def academia
  end

  def computing
  end

  def other
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/controllers/tefl/links_controller.rb
class Tefl::LinksController < ApplicationController
  def index
    @link = Tefl.all
    @new = Tefl.new
  end

  def new
    @new = Tefl.new
  end
  
  def create
    @new = Tefl.new(tefl_params)
    if @new.save
        redirect_to tefl_links_path
        flash[:notice] = "Thank you. Your link has been added."
      else
        render "new"
    end
  end

  def destroy
    @link = Tefl.find(params[:id])
    @link.destroy
    redirect_to tefl_links_path
  end

  def edit
    @link = Tefl.find(params[:id])
  end

  def show
  end

  def update
    @link = Tefl.find(params[:id])
    if Tefl.update(tefl_params)
      redirect_to tefl_links_path
      flash[:notice] = "Thank you. Your post has been updated."
    else
      render "edit"
    end
  end
  
  private
  def tefl_params
    params.require(:tefl).permit(:id, :user_id, :name, :link, :description, :visited, :created_at, :commit)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learning/computing_helper.rb
module Learning::ComputingHelper
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tefl/links_helper.rb
module Tefl::LinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/ackermann.html.erb
<h1>The Ackermann Algorithm</h1>

<h3>The algorithm (in Ruby)</h3>

<pre>
  def ack(m, n)
    if m == 0
      n + 1
    elsif n == 0
      ack(m - 1, 1)
    else
      ack(m - 1, ack(m, n - 1))
    end
  end
</pre>

<p>Large values can result in a lot of processing, so please only enter values from the table below.</p>

<table>
  <thead>
    <tr>
      <td>n/m</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>
      <td>5+</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td style="background:green"></td>
      <td style="background:green"></td>
      <td style="background:green"></td>
      <td style="background:green"></td>
      <td style="background:green"></td>
      <td style="background:red"></td>
    </tr>
    <tr>
      <td>1-9</td>
      <td style="background:green"></td>
      <td style="background:green"></td>
      <td style="background:green"></td>
      <td style="background:green"></td>
      <td style="background:red"></td>
      <td style="background:red"></td>
    </tr>
    <tr>
      <td>10-1000</td>
      <td style="background:green"></td>
      <td style="background:green"></td>
      <td style="background:green"></td>
      <td style="background:red"></td>
      <td style="background:red"></td>
      <td style="background:red"></td>
    </tr>
    <tr>
      <td>1001+</td>
      <td style="background:red"></td>
      <td style="background:red"></td>
      <td style="background:red"></td>
      <td style="background:red"></td>
      <td style="background:red"></td>
      <td style="background:red"></td>
    </tr>
  </tbody>
</table>

<%= form_for @ack do |f| %>
  <%= f.text_field :m %>
  <%= f.text_field :n %>
<% end %>

app/views/projects/bowling.html.erb
    <h1>Let's go bowling!</h1>
    <p>Slide the slider and click bowl!</p>
    <p>The nearer the slider is to the middle, the more skittles you'll knock down.</p>
    <div id="controls">
      <input type="range" id="throwAngle" min="-10" max="10">
      <button id="bowl" autofocus>Bowl!</button>
    </div>
    <table id="player1">
      <tr id="tableHead">
        <th>Frame</th>
        <th>1st ball</th>
        <th>2nd ball</th>
        <th>Frame total</th>
      </tr>
      <tr id="frame1">
        <td>1st</td>
        <td id="ball1"></td>
        <td id="ball2"></td>
        <td id="ball3"></td>
      </tr>
      <tr id="frame2">
        <td>2nd</td>
        <td id="ball1"></td>
        <td id="ball2"></td>
        <td id="ball3"></td>
      </tr>
      <tr id="frame3">
        <td>3rd</td>
        <td id="ball1"></td>
        <td id="ball2"></td>
        <td id="ball3"></td>
      </tr>
      <tr id="frame4">
        <td>4th</td>
        <td id="ball1"></td>
        <td id="ball2"></td>
        <td id="ball3"></td>
      </tr>
      <tr id="frame5">
        <td>5th</td>
        <td id="ball1"></td>
        <td id="ball2"></td>
        <td id="ball3"></td>
      </tr>
      <tr id="frame6">
        <td>6th</td>
        <td id="ball1"></td>
        <td id="ball2"></td>
        <td id="ball3"></td>
      </tr>
      <tr id="frame7">
        <td>7th</td>
        <td id="ball1"></td>
        <td id="ball2"></td>
        <td id="ball3"></td>
      </tr>
      <tr id="frame8">
        <td>8th</td>
        <td id="ball1"></td>
        <td id="ball2"></td>
        <td id="ball3"></td>
      </tr>
      <tr id="frame9">
        <td>9th</td>
        <td id="ball1"></td>
        <td id="ball2"></td>
        <td id="ball3"></td>
      </tr>
      <tr id="frame10">
        <td>10th</td>
        <td id="ball1"></td>
        <td id="ball2"></td>
        <td id="ball3"></td>
      </tr>
      <tr id="results">
        <td>Results</td>
        <td></td>
        <td></td>
        <td id="total"></td>
      </tr>

app/views/projects/fourletters.html.erb
    <h4><u>How to play</u></h4>
    <p>
        I've thought of a word. My word has four letters. Your task is to guess my word. Every time you make a guess I'll tell you how many of the letters in your word are <b>R</b>ight, but in the <b>W</b>rong place in the first column, and how many are <b>R</b>ight and in the <b>R</b>ight place in the second column.
    </p>
    <P>
        Good luck!
    </P>
        Guess the word: <input type="text" id="guess" maxlength="4" onchange="play()" autofocus>
        <button onclick="play()">Guess!</button><span class="mob">Press enter on your keyboard to guess.</span>
    <table id="fourlettertable">
        <thead>
            <tr>
                <th>Right letter <br>Wrong place</th>
                <th>Right letter <br>Right place</th>
                <th>Guess</th>
            </tr>
        </thead>
        <tbody id="list">
            
        </tbody>
    </table>

app/views/projects/index.html.erb
<h1>My Programming Projects</h1>
<p>Choose a project from the "projects" tab to see what I've been doing.</p>

app/views/projects/pythagorus.html.erb
<h1>Projects#pythagorus</h1>
<p>Find me in app/views/projects/pythagorus.html.erb</p>

app/views/projects/thermostat.erb
<container id="thermostat-container">
<div id="thermostat">
  <textarea id="temperature_display" rows="1" cols="2" disabled></textarea><br />
  <p id="powerSaving" style="margin: 0px;">PowerSaving is on</p>
  <button type="button" id="psm_toggle_button">Turn PowerSaving off</button><br /><br />
  <input id="temperatureSlider" type="range" min="10" max="32" /> <br />
  <button type="button" id="down_button">-</button>
  <button type="button" id="up_button">+</button><br />
  <button type="button" id="reset_button">RESET</button><br />

  <label for="city">
    Weather for: <input type="text" id="city" placeholder="enter location">
  </label>

  <div id="show_weather">
    <p>The weather in: <span id="city_span"></span></p>
    <p>The weather is: <span id="current_weather"></span></p>
    <p>The temperature is: <span id="temperature_outside"></span></p>
  </div>
</div>
</container>

app/views/tefl/links/create.html.erb
<h1>Tefl::Links#create</h1>
<p>Find me in app/views/tefl/links/create.html.erb</p>

app/views/tefl/links/destroy.html.erb
<h1>Tefl::Links#destroy</h1>
<p>Find me in app/views/tefl/links/destroy.html.erb</p>

app/views/tefl/links/edit.html.erb
<h1>Edit <%= @link.name %></h1>
<%= form_for @link, url: {action: "update"}, html: {class: "blob"} do |f| %>
  <table>
    <tr><td>Name of link:</td><td><%= f.text_field :name %></td></tr>
    <tr><td>Link address:</td><td><%= f.text_field :link %></td></tr>
    <tr><td>Description:</td><td><%= f.text_area :description %></td></tr>
  </table>
  <%= f.submit "Update link" %>
<% end %>

app/views/tefl/links/index.html.erb
<h1>Useful Sites for English Learners</h1>

<% @link.each do |l| %>
  <div class="blob">
    <h3><%= link_to l.name, l.link %><small> <%= link_to "edit", edit_tefl_link_path(l)%> | <%= link_to "delete", tefl_link_path(l), method: :delete %></small></h3>
    <p><%= link_to "Got to Site", l.link %></p>
    <p><%= l.description %></p>
    <p class="created">Uploaded: <%= l.created_at %></p>
  </div>
<% end %>
<h1>Add a link</h1>
<%= form_for @new, url: {action: "create"}, html: {class: "blob"} do |f| %>
<table>
  <tr><td>Name<span class="nomob"> of link</span>:</td><td><%= f.text_field :name %></td></tr>
  <tr><td>Link<span class="nomob"> address</span>:</td><td><%= f.text_field :link, value: "http://" %></td></tr>
  <tr><td>Desc<span class="nomob">ription</span>:</td><td><%= f.text_area :description %></td></tr>
</table>
  <%= f.submit "Add link" %>
<% end %>

app/views/tefl/links/new.html.erb
<h1>Add a link</h1>
<%= form_for @new, url: {action: "create"}, html: {class: "blob"} do |f| %>
<table>
  <tr><td>Name of link:</td><td><%= f.text_field :name %></td></tr>
  <tr><td>Link address:</td><td><%= f.text_field :link, value: "http://" %></td></tr>
  <tr><td>Description:</td><td><%= f.text_area :description %></td></tr>
</table>
  <%= f.submit "Add link" %>
<% end %>

app/views/tefl/links/show.html.erb
<h1>Tefl::Links#show</h1>
<p>Find me in app/views/tefl/links/show.html.erb</p>

app/views/tefl/links/update.html.erb
<h1>Tefl::Links#update</h1>
<p>Find me in app/views/tefl/links/update.html.erb</p>